Re-Add (Local) support for nerd fonts
elisescu/tty-share pull request #26
Opened 2020-12-14 06:00 UTC by matthewstrasiotto

Resolves #15 .

The changes made here are (mostly) copied across from https://github.com/elisescu/tty-server/pull/16 , with slight modifications to fit new path / routing structures.

As yet - only tested on local session due to #24 , and I'm not sure about the cachability of the new (heavy) assets.

I'll run a local proxy & see if I need to replicate the static asset structure between the two.

For now, they appear at `localhost:8000/s/local/static/fonts/`. I imagine that in public sessions they will appear at `url/s/[sessionid]/static/fonts/`.

Ideally these would sit behind some cloudflare/cloudfront cdn type service, as they're not lightweight dependencies.

2020-12-14 06:11 UTC, matthewstrasiotto commented
Tested via local proxy- It seems to work perfectly fine behind the proxy, though I can't comment on the performance / whether different sessions need to backhaul these assets for each session between the sharing session to the proxy or not.

2020-12-15 01:00 UTC, matthewstrasiotto commented
Latest pushes change the font source to a CDN for (ideally) reduced load on the server, and no extra load on the proxy as a result of delivering these font assets. 

There's a small loading time for the real fontset to arrive locally, wherein it falls back to courier-new, then system monospace. 

For now, this isn't ready to merge until I can squash all inclusions of the font assets since they're large, and deprecated, & shouldn't make it into the main repo index.

2020-12-18 05:18 UTC, matthewstrasiotto commented
I've migrated the font assets to a CDN with an external stylesheet that references them corectly.
This alleviates annoying config between the go server's route config, and webpacks's asset packing, keeps the repo from bloating with binary assets, & should impose no extra load on the server.

2020-12-20 09:00 UTC, elisescu requested changes
I had a few inline comments - there are some leftovers that can be removed, as they don't seem to be needed with this new CDN change.
I like the CDN change better than including the fonts in the binary. 
I didn't forget about your original change in tty-server :) , and wanted to include it in this version 2 but it became very complex to mess with the paths of resources given how they are routed by the proxy. Also the binary became too big and I decided to leave them out - I want to keep the binary as small as possible.
But great idea with having them on a CDN, and a fallback font to use if/when CDN is down.

2021-01-07 03:56 UTC, matthewstrasiotto commented
> I didn't forget about your original change in tty-server :) , and wanted to include it in this version 2 but it became very complex to mess with the paths of resources given how they are routed by the proxy.

Trust me- *I know*

Though the CDN is overall probably going to be better (less load on proxies & less overhead bandwidth from session hosts), the main motivation for the switch was to avoid stuffing with the routing paths.

2021-01-07 04:14 UTC, matthewstrasiotto commented on server/frontend/webpack.config.js
> +          }
Done

2021-01-07 04:16 UTC, matthewstrasiotto commented
@elisescu , thank you for the observations, you're absolutely right, the dependencies added to `package.json`, `package-lock.json` & `webpack.config.js` were redundant.

2021-01-07 20:43 UTC, elisescu approved these changes
Looks good :)

2021-01-07 20:43 UTC, merged

2021-01-07 20:44 UTC, elisescu commented
Thank you for your contribution